name: universal-object-mapping
include:
  - path:
      - ./services/orchestrator/docker-compose.yml
      - ./langgraph-override.compose.yml
services:
  # orchestrator:
  #   build:
  #     context: ./services/orchestrator
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ./services/orchestrator/.env
  #   environment:
  #     - XRG13_SSH_USERNAME=${XRG13_SSH_USERNAME}
  #     # e.g. ~/.ssh/id_ed25519; key is expected to be passwordless
  #     - XRG13_SSH_PRIVATE_KEY_PATH=${XRG13_SSH_PRIVATE_KEY_PATH}
  #   volumes:
  #     - ${XRG13_SSH_PRIVATE_KEY_PATH}:/root/.ssh/xrg13_key:ro
  #   restart: unless-stopped
  #   # depends_on:
  #   # - dotnet-service
  #   # - java-service

  ollama-autossh-tunnel:
    image: jnovack/autossh:2.1.0
    environment:
      - SSH_REMOTE_USER=${XRG13_SSH_USERNAME}
      - SSH_REMOTE_HOST=xrg13.ms.mff.cuni.cz
      - SSH_REMOTE_PORT=1302
      - SSH_TUNNEL_PORT=11434
      - SSH_BIND_IP=0.0.0.0
      - SSH_TARGET_HOST=localhost
      - SSH_TARGET_PORT=11434
      - SSH_MODE=-L
      - SSH_STRICT_HOST_IP_CHECK=false
    ports:
      - "${OLLAMA_PORT}:11434"
    restart: unless-stopped
    volumes:
      - ${XRG13_SSH_PRIVATE_KEY_PATH}:/id_rsa
    dns:
      - 8.8.8.8
      - 4.2.2.4
    # networks:
    #   - ollama

  dotnet-service:
    build:
      context: ./services/dotnet-service
      dockerfile: Dockerfile
    ports:
      - "${DOTNET_SERVICE_PORT}:5073"
    environment:
      - MSSQL_HOST=mssql_db
      - MSSQL_PORT=1433
      - MSSQL_USER=${MSSQL_USER}
      - MSSQL_PASSWORD=${MSSQL_PASSWORD}
    restart: unless-stopped
    depends_on:
      - mssql_db

  java-service:
    build:
      context: ./services/java-services
      dockerfile: Dockerfile
    ports:
      - "${JAVA_SERVICE_PORT}:8080"
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=${NEO4J_USERNAME}
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=${NEO4J_PASSWORD}
      - SPRING_DATA_MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}
    restart: unless-stopped
    depends_on:
      - neo4j
      - mongodb

  mssql_db:
    build:
      context: ./ORMConvertor
      dockerfile: database.Dockerfile
    ports:
      - "${MSSQL_PORT}:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
      - MSSQL_PID=Developer
    restart: unless-stopped
    volumes:
      - mssql_data:/var/opt/mssql

  mongodb:
    image: mongo:8.2.6
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_PASSWORD=${MONGODB_PASSWORD}
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
      - ./services/etl/mongodb/init-mongodb.sh:/docker-entrypoint-initdb.d/init-mongodb.sh

  neo4j:
    image: neo4j:2026.02.2
    ports:
      - "${NEO4J_BROWSER_PORT}:7474"
      - "${NEO4J_PORT}:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
    restart: unless-stopped
    volumes:
      - neo4j_data:/data
      - ./services/etl/neo4j:/neo4j-etl

  postgres:
    image: postgres:18.3
    ports:
      - "5632:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=uom
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: pg_isready -U postgres
      start_period: 10s
      timeout: 1s
      retries: 5
      interval: 60s
      start_interval: 1s

  mongodb-relational-migrator:
    image: public.ecr.aws/v4d7k6c9/relational-migrator:1.15.3
    ports:
      - "8090:8080"
    volumes:
      - mongodb_migrator_data:/root/Migrator
      # MIGRATOR_PATH_DRIVER - optional - Path to a local JDBC driver to mount
      - ${MIGRATOR_PATH_DRIVER:-/dev/null}:/opt/mongodb-relational-migrator/lib/app/lib/driver.jar
    restart: unless-stopped
    depends_on:
      - mongodb
      - mssql_db

volumes:
  mssql_data:
  mongodb_data:
  neo4j_data:
  postgres_data:
  mongodb_migrator_data:

# networks:
#   ollama:
