services:
  langgraph-api:
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /deps/orchestrator/src
          initial_sync: true
        - action: sync
          path: ./scripts
          target: /deps/orchestrator/scripts
          initial_sync: true
        - action: rebuild
          path: pyproject.toml
    networks:
      - default
      - uom
      - daytona-uom
      - ollama
    # environment:
    #   - REDIS_URI=redis://langgraph-redis:6379
    #   - POSTGRES_URI=postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
    #   - NEO4J_DATABASE=neo4j
    #   - NEO4J_USERNAME=${NEO4J_USERNAME}
    #   - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    #   - NEO4J_URI=neo4j://neo4j:7687
    #   - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}
    #   - MSSQL_HOST=mssql_db
    #   - MSSQL_PORT=1433
    #   - MSSQL_USER=${MSSQL_USER}
    #   - MSSQL_PASSWORD=${MSSQL_PASSWORD}
    #   - DB_TOOLBOX_URI=http://db-toolbox:5000
  langgraph-redis:
    ports:
      - "${REDIS_PORT}:6379"

networks:
  uom:
    external: true
    name: uom
  daytona-uom:
    external: true
    name: daytona-uom
