services:
  api:
    environment:
      # - OTEL_EXPORTER_OTLP_ENDPOINT=https://logfire-eu.pydantic.dev
      # - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Bearer pylf_v1_eu_NWM7wqMDnsBcp0mMVpXQQlpBgTrccq6p1BTyv0jS2Bp9
      # - OTEL_COLLECTOR_ENDPOINT_URL=https://logfire-eu.pydantic.dev
      # - OTEL_COLLECTOR_API_KEY=pylf_v1_eu_NWM7wqMDnsBcp0mMVpXQQlpBgTrccq6p1BTyv0jS2Bp9
      - PROXY_DOMAIN=localhost:4000
      - PROXY_TEMPLATE_URL=http://localhost:4000/{{PORT}}-{{sandboxId}}
      # - OTEL_COLLECTOR_ENDPOINT_URL=http://jaeger:4318/v1
      - OTEL_ENABLED=false
      - PUBLIC_OIDC_DOMAIN=http://localhost:5356/dex
    networks:
      - daytona-uom

  proxy:
    environment:
      - OIDC_PUBLIC_DOMAIN=http://localhost:5356/dex
    networks:
      - daytona-uom

  runner:
    # environment:
    #   - OTEL_LOGGING_ENABLED=true
    #   - OTEL_TRACING_ENABLED=true
    #   - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    #   - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Bearer otel_collector_api_key
    networks:
      - daytona-uom
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  dex:
    volumes:
      - ../../../services/daytona/dex/config.yaml:/etc/dex/config.yaml
    ports: !override
      - 5356:5556

  registry:
    ports: !override
      - 6058:6000
  
  maildev: !reset null

  jaeger: !reset null
  
  otel-collector: !reset null

networks:
  daytona-uom:
    external: true
    name: daytona-uom
