services:
  api:
    environment:
      - PROXY_DOMAIN=proxy.daytona.${PRODUCTION_DOMAIN_OR_IP}
      - PROXY_TEMPLATE_URL=https://{{PORT}}-{{sandboxId}}.proxy.daytona.${PRODUCTION_DOMAIN_OR_IP}
      - PROXY_PROTOCOL=https
      
      - DASHBOARD_URL=https://daytona.uom.dyn.cloud.e-infra.cz/dashboard
      - DASHBOARD_BASE_API_URL=https://daytona.${PRODUCTION_DOMAIN_OR_IP}
      
      - PUBLIC_OIDC_DOMAIN=https://daytona.${PRODUCTION_DOMAIN_OR_IP}/dex
      
      - SSH_GATEWAY_URL=daytona.${PRODUCTION_DOMAIN_OR_IP}:2222
      - SSH_GATEWAY_COMMAND=ssh -p 2222 {{TOKEN}}@daytona.${PRODUCTION_DOMAIN_OR_IP}
      - OTEL_ENABLED=false
    networks:
      - uom

  proxy:
    environment:
      - OIDC_PUBLIC_DOMAIN=https://daytona.${PRODUCTION_DOMAIN_OR_IP}/dex
      - PROXY_PROTOCOL=https
      - COOKIE_DOMAIN=proxy.daytona.${PRODUCTION_DOMAIN_OR_IP}
    networks:
      - uom

  runner:
    networks:
      - uom
    extra_hosts:
      - "host.docker.internal:${OUTER_HOST_GATEWAY_IP:-host-gateway}"
  
  dex:
    volumes:
      - ../../../services/daytona/dex/config.yaml:/etc/dex/config.yaml
    ports: !override
      - 5356:5556
    networks:
      - uom

  registry:
    ports: !override
      - 6058:6000
  
  ssh-gateway:
    networks:
      - uom
  
  maildev: !reset null

  jaeger: !reset null
  
  otel-collector: !reset null

networks:
  uom:
    external: true
    name: uom
