"""Utilities for deterministic checks on translation outputs and validation states in React Agent.

This module implements deterministic checks and validations on translation outputs. It evaluates
the structure of generated Java/C# source code, identifies disallowed helper constructs, searches
message histories for compiler outcomes, and compiles structured feedback messages to steer
the LLM generation nodes back to compliance before completing a graph run.
"""

import logging
from typing import Any, Literal

from langchain_core.messages import HumanMessage

from react_agent.constants import FrameworkEnum, TranslationType
from react_agent.state import State
from react_agent.utils import get_message_text

logger = logging.getLogger(__name__)


def _contains_structured_code(code: str | None) -> bool:
    """Evaluate whether a generated code block contains actual programming declarations.

    This function operates on a heuristic to prevent the LLM from returning markdown prose or
    conversational text in place of valid source code.

    Args:
        code: The raw string payload returned by the LLM.

    Returns:
        bool: True if the code contains class or record declarations, indicating structured code;
            False otherwise.
    """
    if code is None:
        return False
    return bool(code.strip()) and "class " in code


def _contains_validation_harness_payload(code: str | None) -> bool:
    """Verify that execution harness wrappers have not been accidentally leaked into query files.

    The translation agent is required to return clean production query code in `translated_query_code`,
    while keeping isolated execution scaffolding in `validation_harness_code`. This check searches
    for terms associated with the validation harness to flag leaks.

    Args:
        code: The raw query code string generated by the agent.

    Returns:
        bool: True if validation harness terms are detected, indicating a separation violation;
            False otherwise.
    """
    if code is None:
        return False

    lower_code = code.lower()
    tokens = (
        "validation_harness",
        "queryvalidationharness",
        "validationharness",
    )
    return any(token in lower_code for token in tokens)


def _message_contains_marker(messages: list[Any], marker: str) -> bool:
    """Search backward through the message history to check if a specific string marker is present.

    We iterate in reverse order because recent outcomes (e.g. latest compilation or equivalence reports)
    are at the end of the list and represent the current execution state.

    Args:
        messages: A list of standard LangChain or LangGraph messages.
        marker: Substring key to search for (e.g. "[Query Equivalence Passed]").

    Returns:
        bool: True if the marker is found in any message content; False otherwise.
    """
    for message in reversed(messages):
        content = ""
        try:
            content = get_message_text(message)
        except Exception:
            raw_content = getattr(message, "content", "")
            content = str(raw_content)
        if marker in content:
            return True
    return False


def _find_unexpected_tokens(
    source_code: str | None,
    translated_code: str | None,
    tokens: tuple[str, ...],
) -> list[str]:
    """Identify synthetic parameter tokens introduced by the translation that were absent in the source.

    This helper is used to prevent the LLM from introducing mock variables (like sorting direction fields)
    into the query method signatures. These must instead be configured in the test harness.

    Args:
        source_code: The original source query code.
        translated_code: The newly translated target query code.
        tokens: A tuple of lowercase substrings representing restricted parameter names.

    Returns:
        list[str]: A list of restricted tokens found in the translated code but not in the source.
    """
    if not (source_code or "").strip():
        return []

    source = (source_code or "").lower()
    translated = (translated_code or "").lower()
    return [token for token in tokens if token in translated and token not in source]


def _latest_validation_outcome(
    messages: list[Any],
    passed_marker: str,
    failed_marker: str,
) -> Literal["passed", "failed", "missing"]:
    """Scan the message history in reverse to detect the most recent compiler validation result.

    This helps determine if the latest sandbox run completed successfully or failed due to syntax.

    Args:
        messages: The chronological list of thread messages.
        passed_marker: The outcome token indicating compile success (e.g. "Validation Passed]").
        failed_marker: The outcome token indicating compile failure (e.g. "Validation Failed]").

    Returns:
        Literal["passed", "failed", "missing"]: The string status representing the latest execution result.
    """
    for message in reversed(messages):
        content = ""
        try:
            content = get_message_text(message)
        except Exception:
            raw_content = getattr(message, "content", "")
            content = str(raw_content)

        if passed_marker in content:
            return "passed"
        if failed_marker in content:
            return "failed"

    return "missing"


def _validate_query_code_structure(
    destination_target: FrameworkEnum | None,
    translated_query_code: str | None,
    source_query_code: str | None,
) -> list[str]:
    """Execute target-specific syntax checks on the translated query code.

    This function enforces framework-specific API guidelines for the Spring ecosystem,
    ensuring the LLM uses modern declarative or fluent DSL APIs rather than unsafe raw Cypher or SQL string composition.

    Args:
        destination_target: The target Java framework mapping type.
        translated_query_code: The translated production query source code.
        source_query_code: The original C# query source code.

    Returns:
        list[str]: A list of validation error descriptions. Empty if structural rules are met.
    """
    errors: list[str] = []

    # 1. Enforce that the translated query contains a structured class block
    if not _contains_structured_code(translated_query_code):
        errors.append(
            "translated_query_code must contain concrete Java/C# class-based code, not prose."
        )
        return errors

    assert translated_query_code is not None
    lower_code = translated_query_code.lower()

    # 2. Prevent the introduction of dynamic paging/sorting parameters not defined in C# LINQ
    unexpected_sort_tokens = _find_unexpected_tokens(
        source_query_code,
        translated_query_code,
        ("sortbyfield", "sortdirection", "ascending", "descending"),
    )
    if unexpected_sort_tokens:
        errors.append(
            "translated_query_code introduced synthetic ordering/config inputs not present in source query "
            f"({', '.join(unexpected_sort_tokens)}). Keep translated_query_code equivalent to the source query "
            "and place deterministic validation setup in validation_harness_code."
        )

    # 3. Enforce Spring Data MongoDB specific APIs
    if destination_target == FrameworkEnum.JAVA_SPRING_DATA_MONGODB:
        for token in ("mongotemplate", "criteria", "query"):
            if token not in lower_code:
                errors.append(
                    "Spring Data MongoDB query must use MongoTemplate with Query/Criteria API."
                )
                break

    # 4. Enforce Spring Data Neo4j specific Cypher-DSL APIs
    if destination_target == FrameworkEnum.JAVA_SPRING_DATA_NEO4J:
        if "neo4jtemplate" not in lower_code:
            errors.append("Spring Data Neo4j query must use Neo4jTemplate.")

        # Cypher queries must use Spring's Cypher-DSL core classes rather than concatenated raw strings
        uses_cypher_dsl = any(
            token in translated_query_code
            for token in (
                "org.neo4j.cypherdsl.core",
                "Cypher.",
                "Statement",
                "Renderer",
            )
        )
        if not uses_cypher_dsl:
            errors.append(
                "Spring Data Neo4j query must use Cypher-DSL syntax (not raw Cypher string composition)."
            )

    return errors


def _validation_outcome_by_id(
    messages: list[Any],
    tool_call_id: str,
) -> Literal["passed", "failed", "pending"]:
    """Query the message trace to retrieve the specific outcome of a tool execution ID.

    This helps correlate parallel compiler tool runs (e.g. source validation vs target validation)
    individually using their static tool call identifiers.

    Args:
        messages: Chronological message history.
        tool_call_id: The static tool call identifier associated with the validation run.

    Returns:
        Literal["passed", "failed", "pending"]: Outcome state.
    """
    for msg in reversed(messages):
        if getattr(msg, "type", "") == "tool" and getattr(msg, "tool_call_id", "") == tool_call_id:
            content = str(getattr(msg, "content", ""))
            if "Validation Passed]" in content:
                return "passed"
            if "Validation Failed]" in content:
                return "failed"
    return "pending"


def _deterministic_translation_issues(
    state: State,
    translated_schema_code: str | None,
    translated_query_code: str | None,
    validation_harness_code: str | None,
    messages: list[Any],
) -> tuple[list[str], bool, bool]:
    """Inspect the current translation state and tool traces to assess if validation parameters are satisfied.

    This function compiles structural violations, compiler failures, and equivalence discrepancies.
    It returns a boolean state signaling if the schema or query translation can be marked complete.

    Args:
        state: The current LangGraph service execution State.
        translated_schema_code: The generated target entity mapping code.
        translated_query_code: The generated target query code.
        validation_harness_code: The generated target test execution harness code.
        messages: Complete conversation thread messages.

    Returns:
        tuple[list[str], bool, bool]: A tuple containing:
            - A list of identified issues (empty if compliant).
            - A boolean indicating if the schema translation succeeded.
            - A boolean indicating if the query translation succeeded.
    """
    issues: list[str] = []
    schema_ok = True
    query_ok = True

    # 1. Evaluate Schema translation if required
    if state.translation_type in {TranslationType.SCHEMA, TranslationType.BOTH}:
        if not _contains_structured_code(translated_schema_code):
            schema_ok = False
            issues.append(
                "translated_schema_code is missing or not valid class-based code."
            )

    # 2. Evaluate Query translation if required
    if state.translation_type in {TranslationType.QUERY, TranslationType.BOTH}:
        if not _contains_structured_code(validation_harness_code):
            query_ok = False
            issues.append(
                "validation_harness_code must contain class-based validation helper code for query metadata checks."
            )

        if _contains_validation_harness_payload(translated_query_code):
            query_ok = False
            issues.append(
                "translated_query_code must exclude validation harness content. Keep harness in validation_harness_code only."
            )

        query_structure_issues = _validate_query_code_structure(
            state.destination_target,
            translated_query_code,
            state.source_query_code,
        )
        if query_structure_issues:
            query_ok = False
            issues.extend(query_structure_issues)

        # 3. Assert that both source and target compilation runs succeeded in Daytona sandboxes
        source_validation = _validation_outcome_by_id(messages, "query_val_1")
        if source_validation == "failed":
            query_ok = False
            issues.append(
                "Source validation failed. Source query/schema must be fixed before continuing."
            )
        elif source_validation != "passed":
            query_ok = False
            issues.append(
                "Source validation must pass before query translation can finish."
            )

        target_validation = _validation_outcome_by_id(messages, "query_val_2")
        if target_validation != "passed":
            query_ok = False
            issues.append(
                "Target validation must pass before query translation can finish."
            )

        # 4. Assert that the DeepDiff query output equivalence check has completed successfully
        if not _message_contains_marker(messages, "[Query Equivalence Passed]"):
            query_ok = False
            issues.append(
                "check_query_equivalence must pass before query translation can finish."
            )

    return issues, schema_ok, query_ok


def _deterministic_feedback_message(issues: list[str]) -> HumanMessage:
    """Compile structured feedback formatting numbered issues to direct translation corrections.

    Args:
        issues: A list of identified issues/compilation faults.

    Returns:
        HumanMessage: A LangChain message containing repair instructions.
    """
    numbered_issues = "\n".join(
        f"{idx + 1}. {issue}" for idx, issue in enumerate(issues)
    )
    feedback = (
        "Your previous translation attempt cannot be accepted yet.\n"
        "Fix all deterministic issues below, then return structured output again:\n"
        f"{numbered_issues}\n"
        "For query translations, keep translated_query_code and validation_harness_code separate.\n"
        "Required tool sequence for query translations:"
        " parallel source and target validation -> check_query_equivalence."
    )
    return HumanMessage(content=feedback)

