/**
 * @file types.ts
 * @description Holds TypeScript interface and enum definitions for the Universal Object Mapping (UOM) frontend.
 * Maps state fields of the LangGraph orchestrator, execution configurations, and platform types.
 */

/**
 * Represents validation outputs generated by compiling/executing source or target code in Daytona sandboxes.
 */
export interface QueryValidationResults {
	/** Total number of records returned by the query. */
	count?: number;
	/** First record sample returned by the database. */
	firstSample?: any;
	/** Last record sample returned by the database. */
	lastSample?: any;
	/** Any compilation or execution error messages from container stdout/stderr. */
	error?: string | null;
	/** Compiled SQL query string generated by Entity Framework or NHibernate. */
	sqlString?: string;
	/** Generated Cypher query string for Spring Data Neo4j. */
	cypher?: string;
	/** Generated MongoDB query JSON string. */
	mongoQuery?: string;
	/** Generated MongoDB aggregation pipeline JSON string. */
	mongoAggregation?: string;
}

/**
 * Output structure from semantic query equivalence checks using DeepDiff.
 */
export interface QueryEquivalenceDeepDiff {
	/** Custom mapping for LLM to understand which sample is which. */
	deepdiff_mapping?: any;
	/** Difference details in document counts. */
	count_diff?: any;
	/** Differences found between the first document samples. */
	first_sample_diff?: any;
	/** Differences found between the last document samples. */
	last_sample_diff?: any;
	/** Equivalence calculation runtime errors, if any. */
	error?: string | null;
}

/**
 * Configuration schema for the UOM Translator frontend.
 * Persisted in localStorage and passed to the LangGraph execution runtime.
 */
export interface UomConfig {
	/** Endpoint hostname/port for the local Ollama instance (e.g. http://localhost:11434). */
	ollamaHost: string;
	/** The specific model name to run (e.g. einfra/kimi-k2.6, ollama/qwen3-coder:30b). */
	model: string;
	/** Base URL for OpenAI-compatible LLM endpoints (e.g. e-INFRA AI services). */
	openaiApiUrl: string;
	/** API authorization key for OpenAI/e-INFRA endpoints. */
	openaiApiKey: string;
	/** Connection string to the source MS SQL Server instance. */
	mssqlConnectionString: string;
	/** URI for target MongoDB instance. */
	mongodbUri: string;
	/** Connection URI for target Neo4j Graph database. */
	neo4jUri: string;
	/** Password for authentication with Neo4j. */
	neo4jPassword: string;
	/** Endpoint URL of the Daytona API server. */
	daytonaApiUrl: string;
	/** API token for Daytona container orchestration. */
	daytonaApiKey: string;
	/** Target cloud region for Daytona sandbox containers (e.g. 'us', 'eu'). */
	daytonaTarget: "eu" | "us";
	/** Compilation sandbox execution limit in seconds. */
	daytonaTimeout: number;
	/** URI of the Database Toolbox MCP server wrapper. */
	dbToolboxUri?: string;
	/** URI of the MongoDB MCP server wrapper. */
	mongodbMcpUri?: string;
}

/**
 * Represents the complete execution state shared with the LangGraph state orchestrator.
 * Mirrors the Python LangGraph `State` schema exactly.
 */
export interface BackendState {
	/** Main conversational messages history including user prompts and agent responses. */
	messages?: any[];
	/** Input source code schema block provided by the user (C# EF Core / NHibernate / Dapper). */
	source_schema_code?: string | null;
	/** Input query C# code block provided by user. */
	source_query_code?: string | null;
	/** Desired translation scope ('schema', 'query', or 'both'). */
	translation_type?: string | null;
	/** Human-friendly name of the source framework (e.g. ".NET Entity Framework Core"). */
	source_target?: string | null;
	/** Explicit version parameter of the source framework. */
	source_target_version?: string | null;
	/** Human-friendly name of the target framework (e.g. "Java Spring Data MongoDB"). */
	destination_target?: string | null;
	/** Explicit version parameter of the target framework. */
	destination_target_version?: string | null;
	/** Generated target model/entity Java code translation. */
	translated_schema_code?: string | null;
	/** Generated target query Java code translation. */
	translated_query_code?: string | null;
	/** Extracted validation schemas for compile verification. */
	source_validation_schema_code?: string | null;
	/** Generated compilation project harness for .NET code. */
	source_validation_harness_code?: string | null;
	/** Generated target entities class representation for compiling. */
	target_validation_schema_code?: string | null;
	/** Generated compilation project harness for Java code. */
	target_validation_harness_code?: string | null;
	/** Accompanying notes or structural advice generated by the LLM advisor. */
	explanation_message?: string | null;
	/** Boolean indicator set when the State Graph terminates. */
	is_last_step?: boolean;
	/** Entrypoint class name for the C# validation harness. */
	source_validation_entry_type_name?: string | null;
	/** Entrypoint class name for the Java validation harness. */
	target_validation_entry_type_name?: string | null;
	/** Structured validation results returned from compile and execute tests on source code. */
	source_query_validation_results?: QueryValidationResults | null;
	/** Structured validation results returned from compile and execute tests on target code. */
	target_query_validation_results?: QueryValidationResults | null;
	/** Mapping of query keys to equivalence diff results. */
	query_equivalence_deep_diffs?: Record<
		string,
		QueryEquivalenceDeepDiff
	> | null;
	/** Live schema structures retrieved from the source database via MCP. */
	schema_context?: string;
	/** Isolated, system-level prompts used internally by the orchestrator. */
	translation_messages?: any[];
	/** Tracked iteration count of input parsing adjustments. */
	extraction_loop_count?: number;
	/** Tracked retry loop count for code generation compilation. */
	translation_loop_count?: number;
}

/**
 * List of enqueued LLMs available for selection in the configurations panel.
 * Comprises local Ollama options and high-performance remote e-INFRA CZ cluster endpoints.
 */
export enum AvailableModel {
	// Ollama Models
	OLLAMA_QWEN3_6_27B = "ollama/qwen3.6:27b",
	OLLAMA_GPT_OSS = "ollama/gpt-oss:latest",
	OLLAMA_QWEN3_CODER_30B = "ollama/qwen3-coder:30b",
	OLLAMA_MISTRAL_SMALL_3_2 = "ollama/mistral-small3.2:latest",

	// EINFRA Models (OpenAI compatible)
	EINFRA_MINI = "einfra/mini",
	EINFRA_CODER = "einfra/coder",
	EINFRA_AGENTIC = "einfra/agentic",
	EINFRA_THINKER = "einfra/thinker",
	EINFRA_QWEN3_CODER = "einfra/qwen3-coder",
	EINFRA_QWEN3_CODER_30B = "einfra/qwen3-coder-30b",
	EINFRA_GPT_OSS_120B = "einfra/gpt-oss-120b",
	EINFRA_LLAMA_4_SCOUT_17B = "einfra/llama-4-scout-17b-16e-instruct",
	EINFRA_DEEPSEEK_V4_PRO = "einfra/deepseek-v4-pro",
	EINFRA_DEEPSEEK_V4_PRO_THINKING = "einfra/deepseek-v4-pro-thinking",
	EINFRA_MISTRAL_LARGE = "einfra/mistral-large",
	EINFRA_KIMI_K2_5 = "einfra/kimi-k2.5",
	EINFRA_KIMI_K2_6 = "einfra/kimi-k2.6",
	EINFRA_QWEN3_5 = "einfra/qwen3.5",
	EINFRA_QWEN3_CODER_NEXT = "einfra/qwen3-coder-next",
	EINFRA_QWEN3_5_122B = "einfra/qwen3.5-122b",
	EINFRA_GLM_4_7 = "einfra/glm-4.7",
	EINFRA_GLM_5 = "einfra/glm-5",
	EINFRA_GLM_5_1 = "einfra/glm-5.1",
}

/**
 * Supported framework types for ORM, ODM, and OGM mapping migrations.
 */
export enum FrameworkType {
	/** Relational source: Entity Framework Core */
	DOTNET_EFCORE = "dotnet_efcore",
	/** Relational source: NHibernate Core */
	DOTNET_NHIBERNATE = "dotnet_nhibernate",
	/** Relational source: Dapper SQL micro-ORM */
	DOTNET_DAPPER = "dotnet_dapper",
	/** NoSQL Document target: Spring Data MongoDB */
	JAVA_SPRING_DATA_MONGODB = "java_spring_data_mongodb",
	/** NoSQL Graph target: Spring Data Neo4j */
	JAVA_SPRING_DATA_NEO4J = "java_spring_data_neo4j",
}

/**
 * Underlying programming language runtimes.
 */
export enum LanguageType {
	/** Microsoft .NET Core (C#) */
	DOTNET = "dotnet",
	/** Oracle/OpenJDK Java (Java) */
	JAVA = "java",
}

/**
 * Translation operation scopes.
 */
export enum TranslationType {
	/** Schema classes/mappings translation only. */
	SCHEMA = "schema",
	/** Database Query translation only. */
	QUERY = "query",
	/** Combined schema definitions and executable query code. */
	BOTH = "both",
}

/**
 * Sandbox Docker container images provisioned via Daytona.
 */
export enum SandboxType {
	/** Sandbox container equipped with .NET 10 SDK and compilation utilities. */
	DOTNET_10_SANDBOX = "dotnet-10-sandbox",
	/** Sandbox container equipped with OpenJDK 25 and Maven/Gradle dependencies. */
	JAVA_25_SANDBOX = "java-25-sandbox",
}

/**
 * Composite structure holding execution details for supported frameworks.
 */
export interface FrameworkInfoType {
	/** Readable layout name of the framework. */
	name: string;
	/** Language ecosystem. */
	language: LanguageType;
	/** Sandbox image type used for compilations. */
	sandbox: SandboxType;
	/** True if the framework serves as an import source. */
	is_source: boolean;
	/** True if the framework serves as an export target. */
	is_target: boolean;
}

/**
 * Structured keys sent via LangGraph custom events.
 * Used to stream remote compilation progress, compile stdout/stderr logs, and container snapshot creation updates.
 */
export enum LanggraphCustomEventKeys {
	/** Notification when a new .NET Daytona container snapshot starts or completes creation. */
	DOTNET_SANDBOX_SNAPSHOT_CREATION = "dotnet_sandbox_snapshot_creation",
	/** Notification when a new Java Daytona container snapshot starts or completes creation. */
	JAVA_SANDBOX_SNAPSHOT_CREATION = "java_sandbox_snapshot_creation",
	/** Compilation/execution standard output logs from the .NET Daytona container. */
	DOTNET_SANDBOX_COMMAND_EXECUTION_STDOUT = "dotnet_sandbox_command_execution_stdout",
	/** Compilation/execution error logs from the .NET Daytona container. */
	DOTNET_SANDBOX_COMMAND_EXECUTION_STDERR = "dotnet_sandbox_command_execution_stderr",
	/** Compilation/execution standard output logs from the Java Daytona container. */
	JAVA_SANDBOX_COMMAND_EXECUTION_STDOUT = "java_sandbox_command_execution_stdout",
	/** Compilation/execution error logs from the Java Daytona container. */
	JAVA_SANDBOX_COMMAND_EXECUTION_STDERR = "java_sandbox_command_execution_stderr",
	/** Fallback event key for unrecognized event payloads. */
	UNKNOWN = "unknown",
}
